# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kv.proto',
  package='kv',
  syntax='proto3',
  serialized_pb=_b('\n\x08kv.proto\x12\x02kv\"-\n\x0fSetValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"]\n\x10SetValueResponse\x12+\n\x06result\x18\x01 \x01(\x0e\x32\x1b.kv.SetValueResponse.Result\"\x1c\n\x06Result\x12\x08\n\x04SUCC\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\"\x1e\n\x0fGetValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"q\n\x10GetValueResponse\x12+\n\x06result\x18\x01 \x01(\x0e\x32\x1b.kv.GetValueResponse.Result\x12\r\n\x05value\x18\x02 \x01(\t\"!\n\x06Result\x12\t\n\x05\x46ound\x10\x00\x12\x0c\n\x08NotFound\x10\x01\x32x\n\x08KeyValue\x12\x35\n\x08SetValue\x12\x13.kv.SetValueRequest\x1a\x14.kv.SetValueResponse\x12\x35\n\x08GetValue\x12\x13.kv.GetValueRequest\x1a\x14.kv.GetValueResponseb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SETVALUERESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='kv.SetValueResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCC', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=128,
  serialized_end=156,
)
_sym_db.RegisterEnumDescriptor(_SETVALUERESPONSE_RESULT)

_GETVALUERESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='kv.GetValueResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Found', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NotFound', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=270,
  serialized_end=303,
)
_sym_db.RegisterEnumDescriptor(_GETVALUERESPONSE_RESULT)


_SETVALUEREQUEST = _descriptor.Descriptor(
  name='SetValueRequest',
  full_name='kv.SetValueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='kv.SetValueRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='kv.SetValueRequest.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=61,
)


_SETVALUERESPONSE = _descriptor.Descriptor(
  name='SetValueResponse',
  full_name='kv.SetValueResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='kv.SetValueResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SETVALUERESPONSE_RESULT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=156,
)


_GETVALUEREQUEST = _descriptor.Descriptor(
  name='GetValueRequest',
  full_name='kv.GetValueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='kv.GetValueRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=188,
)


_GETVALUERESPONSE = _descriptor.Descriptor(
  name='GetValueResponse',
  full_name='kv.GetValueResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='kv.GetValueResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='kv.GetValueResponse.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETVALUERESPONSE_RESULT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=303,
)

_SETVALUERESPONSE.fields_by_name['result'].enum_type = _SETVALUERESPONSE_RESULT
_SETVALUERESPONSE_RESULT.containing_type = _SETVALUERESPONSE
_GETVALUERESPONSE.fields_by_name['result'].enum_type = _GETVALUERESPONSE_RESULT
_GETVALUERESPONSE_RESULT.containing_type = _GETVALUERESPONSE
DESCRIPTOR.message_types_by_name['SetValueRequest'] = _SETVALUEREQUEST
DESCRIPTOR.message_types_by_name['SetValueResponse'] = _SETVALUERESPONSE
DESCRIPTOR.message_types_by_name['GetValueRequest'] = _GETVALUEREQUEST
DESCRIPTOR.message_types_by_name['GetValueResponse'] = _GETVALUERESPONSE

SetValueRequest = _reflection.GeneratedProtocolMessageType('SetValueRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETVALUEREQUEST,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.SetValueRequest)
  ))
_sym_db.RegisterMessage(SetValueRequest)

SetValueResponse = _reflection.GeneratedProtocolMessageType('SetValueResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETVALUERESPONSE,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.SetValueResponse)
  ))
_sym_db.RegisterMessage(SetValueResponse)

GetValueRequest = _reflection.GeneratedProtocolMessageType('GetValueRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETVALUEREQUEST,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.GetValueRequest)
  ))
_sym_db.RegisterMessage(GetValueRequest)

GetValueResponse = _reflection.GeneratedProtocolMessageType('GetValueResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETVALUERESPONSE,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.GetValueResponse)
  ))
_sym_db.RegisterMessage(GetValueResponse)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class KeyValueStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SetValue = channel.unary_unary(
        '/kv.KeyValue/SetValue',
        request_serializer=SetValueRequest.SerializeToString,
        response_deserializer=SetValueResponse.FromString,
        )
    self.GetValue = channel.unary_unary(
        '/kv.KeyValue/GetValue',
        request_serializer=GetValueRequest.SerializeToString,
        response_deserializer=GetValueResponse.FromString,
        )


class KeyValueServicer(object):

  def SetValue(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetValue(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KeyValueServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SetValue': grpc.unary_unary_rpc_method_handler(
          servicer.SetValue,
          request_deserializer=SetValueRequest.FromString,
          response_serializer=SetValueResponse.SerializeToString,
      ),
      'GetValue': grpc.unary_unary_rpc_method_handler(
          servicer.GetValue,
          request_deserializer=GetValueRequest.FromString,
          response_serializer=GetValueResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'kv.KeyValue', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaKeyValueServicer(object):
  def SetValue(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def GetValue(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaKeyValueStub(object):
  def SetValue(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  SetValue.future = None
  def GetValue(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  GetValue.future = None


def beta_create_KeyValue_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  request_deserializers = {
    ('kv.KeyValue', 'GetValue'): GetValueRequest.FromString,
    ('kv.KeyValue', 'SetValue'): SetValueRequest.FromString,
  }
  response_serializers = {
    ('kv.KeyValue', 'GetValue'): GetValueResponse.SerializeToString,
    ('kv.KeyValue', 'SetValue'): SetValueResponse.SerializeToString,
  }
  method_implementations = {
    ('kv.KeyValue', 'GetValue'): face_utilities.unary_unary_inline(servicer.GetValue),
    ('kv.KeyValue', 'SetValue'): face_utilities.unary_unary_inline(servicer.SetValue),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_KeyValue_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  request_serializers = {
    ('kv.KeyValue', 'GetValue'): GetValueRequest.SerializeToString,
    ('kv.KeyValue', 'SetValue'): SetValueRequest.SerializeToString,
  }
  response_deserializers = {
    ('kv.KeyValue', 'GetValue'): GetValueResponse.FromString,
    ('kv.KeyValue', 'SetValue'): SetValueResponse.FromString,
  }
  cardinalities = {
    'GetValue': cardinality.Cardinality.UNARY_UNARY,
    'SetValue': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'kv.KeyValue', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
