// Code generated by protoc-gen-go.
// source: protos/kv.proto
// DO NOT EDIT!

/*
Package kv is a generated protocol buffer package.

It is generated from these files:
	protos/kv.proto

It has these top-level messages:
	SetValueRequest
	SetValueResponse
	GetValueRequest
	GetValueResponse
*/
package kv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetValueResponse_Result int32

const (
	SetValueResponse_SUCC SetValueResponse_Result = 0
	SetValueResponse_FAIL SetValueResponse_Result = 1
)

var SetValueResponse_Result_name = map[int32]string{
	0: "SUCC",
	1: "FAIL",
}
var SetValueResponse_Result_value = map[string]int32{
	"SUCC": 0,
	"FAIL": 1,
}

func (x SetValueResponse_Result) String() string {
	return proto.EnumName(SetValueResponse_Result_name, int32(x))
}
func (SetValueResponse_Result) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type GetValueResponse_Result int32

const (
	GetValueResponse_Found    GetValueResponse_Result = 0
	GetValueResponse_NotFound GetValueResponse_Result = 1
)

var GetValueResponse_Result_name = map[int32]string{
	0: "Found",
	1: "NotFound",
}
var GetValueResponse_Result_value = map[string]int32{
	"Found":    0,
	"NotFound": 1,
}

func (x GetValueResponse_Result) String() string {
	return proto.EnumName(GetValueResponse_Result_name, int32(x))
}
func (GetValueResponse_Result) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type SetValueRequest struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *SetValueRequest) Reset()                    { *m = SetValueRequest{} }
func (m *SetValueRequest) String() string            { return proto.CompactTextString(m) }
func (*SetValueRequest) ProtoMessage()               {}
func (*SetValueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SetValueResponse struct {
	Result SetValueResponse_Result `protobuf:"varint,1,opt,name=result,enum=kv.SetValueResponse_Result" json:"result,omitempty"`
}

func (m *SetValueResponse) Reset()                    { *m = SetValueResponse{} }
func (m *SetValueResponse) String() string            { return proto.CompactTextString(m) }
func (*SetValueResponse) ProtoMessage()               {}
func (*SetValueResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetValueRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *GetValueRequest) Reset()                    { *m = GetValueRequest{} }
func (m *GetValueRequest) String() string            { return proto.CompactTextString(m) }
func (*GetValueRequest) ProtoMessage()               {}
func (*GetValueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetValueResponse struct {
	Result GetValueResponse_Result `protobuf:"varint,1,opt,name=result,enum=kv.GetValueResponse_Result" json:"result,omitempty"`
	Value  string                  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *GetValueResponse) Reset()                    { *m = GetValueResponse{} }
func (m *GetValueResponse) String() string            { return proto.CompactTextString(m) }
func (*GetValueResponse) ProtoMessage()               {}
func (*GetValueResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*SetValueRequest)(nil), "kv.SetValueRequest")
	proto.RegisterType((*SetValueResponse)(nil), "kv.SetValueResponse")
	proto.RegisterType((*GetValueRequest)(nil), "kv.GetValueRequest")
	proto.RegisterType((*GetValueResponse)(nil), "kv.GetValueResponse")
	proto.RegisterEnum("kv.SetValueResponse_Result", SetValueResponse_Result_name, SetValueResponse_Result_value)
	proto.RegisterEnum("kv.GetValueResponse_Result", GetValueResponse_Result_name, GetValueResponse_Result_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for KeyValue service

type KeyValueClient interface {
	SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*SetValueResponse, error)
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
}

type keyValueClient struct {
	cc *grpc.ClientConn
}

func NewKeyValueClient(cc *grpc.ClientConn) KeyValueClient {
	return &keyValueClient{cc}
}

func (c *keyValueClient) SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*SetValueResponse, error) {
	out := new(SetValueResponse)
	err := grpc.Invoke(ctx, "/kv.KeyValue/SetValue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	out := new(GetValueResponse)
	err := grpc.Invoke(ctx, "/kv.KeyValue/GetValue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KeyValue service

type KeyValueServer interface {
	SetValue(context.Context, *SetValueRequest) (*SetValueResponse, error)
	GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
}

func RegisterKeyValueServer(s *grpc.Server, srv KeyValueServer) {
	s.RegisterService(&_KeyValue_serviceDesc, srv)
}

func _KeyValue_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.KeyValue/SetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServer).SetValue(ctx, req.(*SetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValue_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.KeyValue/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeyValue_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kv.KeyValue",
	HandlerType: (*KeyValueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetValue",
			Handler:    _KeyValue_SetValue_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _KeyValue_GetValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("protos/kv.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0xcf, 0x2e, 0xd3, 0x03, 0xb3, 0x84, 0x98, 0xb2, 0xcb, 0x94, 0x2c, 0xb9, 0xf8,
	0x83, 0x53, 0x4b, 0xc2, 0x12, 0x73, 0x4a, 0x53, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84,
	0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x21,
	0x11, 0x2e, 0xd6, 0x32, 0x90, 0x0a, 0x09, 0x26, 0xb0, 0x18, 0x84, 0xa3, 0x94, 0xca, 0x25, 0x80,
	0xd0, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x64, 0xcc, 0xc5, 0x56, 0x94, 0x5a, 0x5c, 0x9a,
	0x53, 0x02, 0xd6, 0xce, 0x67, 0x24, 0xad, 0x97, 0x5d, 0xa6, 0x87, 0xae, 0x4a, 0x2f, 0x08, 0xac,
	0x24, 0x08, 0xaa, 0x54, 0x49, 0x86, 0x8b, 0x0d, 0x22, 0x22, 0xc4, 0xc1, 0xc5, 0x12, 0x1c, 0xea,
	0xec, 0x2c, 0xc0, 0x00, 0x62, 0xb9, 0x39, 0x7a, 0xfa, 0x08, 0x30, 0x2a, 0x29, 0x73, 0xf1, 0xbb,
	0x13, 0x72, 0xa1, 0x52, 0x03, 0x23, 0x97, 0x80, 0x3b, 0x51, 0x8e, 0x71, 0xc7, 0xef, 0x18, 0x1c,
	0x7e, 0x55, 0x84, 0x3b, 0x91, 0x93, 0x8b, 0xd5, 0x2d, 0xbf, 0x34, 0x2f, 0x45, 0x80, 0x41, 0x88,
	0x87, 0x8b, 0xc3, 0x2f, 0xbf, 0x04, 0xc2, 0x63, 0x34, 0xaa, 0xe0, 0xe2, 0xf0, 0x4e, 0xad, 0x04,
	0x9b, 0x2d, 0x64, 0xca, 0xc5, 0x01, 0xf3, 0xb4, 0x90, 0x30, 0x6a, 0x10, 0x80, 0x7d, 0x20, 0x25,
	0x82, 0x2d, 0x5c, 0x40, 0xda, 0xdc, 0x51, 0xb4, 0xb9, 0x63, 0xd3, 0x86, 0xee, 0x83, 0x24, 0x36,
	0x70, 0x74, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xce, 0x1e, 0x70, 0xe1, 0x01, 0x00,
	0x00,
}
